---
- hosts: web
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/mysql.yml
    - vars/apache.yml
    - vars/php.yml
    - vars/firewall.yml
    - vars/nodejs.yml
    - vars/certbot.yml
    - vars/composer.yml
    - vars/supervisor.yml

  vars:
    - update_apt_cache: yes
    - php_version: '8.1'

  roles:
    - role: geerlingguy.firewall
    - role: geerlingguy.mysql
    - role: custom_dependencies
    - role: geerlingguy.apache
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.composer
    - role: geerlingguy.redis
    - role: geerlingguy.nodejs
    - role: geerlingguy.certbot
    - role: ocha.yarn
    - role: geerlingguy.supervisor