---
- name: Copy website content to versioned directory
  synchronize:
    src: "{{ source_directory }}/"
    dest: "{{ new_release_dir }}/"
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=/api/.env"
      - "--chmod=F0640,D0771" # provide here the permission
      - "--chown=www-data:www-data" # provide here the owner and group