# DOCKER TASKS

starter-node-shell: ## Run node container
	docker exec -it node /bin/bash

starter-app-shell: ## Run PHP container
	docker exec -it app /bin/bash

starter-database-shell: ## Run MongoDB container
	docker exec -it database bash
