---
- name: "Install other dependencies."
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl
    - unzip
    - sendmail
    - acl

- name: "Ensure SSH key is generated"
  command: ssh-keygen -t rsa -b 4096 -C "{{git_email}}" -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa

- name: Ensure Jenkins user exists
  user:
    name: jenkins
    state: present

- name: Ensure .ssh directory for Jenkins exists
  file:
    path: "/var/lib/jenkins/.ssh"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

- name: Ensure jenkins_data/starter directory for Jenkins exists
  file:
    path: "/var/jenkins_data/starter"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

- name: Copy Jenkins private SSH key
  copy:
    src: "sensitive/ssh_keys/id_rsa"
    dest: "/var/lib/jenkins/.ssh/id_rsa"
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Copy Jenkins public SSH key
  copy:
    src: "sensitive/ssh_keys/id_rsa.pub"
    dest: "/var/lib/jenkins/.ssh/id_rsa.pub"
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Copy Jenkins SSH private key
  copy:
    src: "sensitive/inventory"
    dest: "/var/jenkins_data/starter/inventory"
    owner: jenkins
    group: jenkins
    mode: '0644'

# Set some settings in ~/.gitconfig
- name: Setup git name
  git_config:
    name: user.name
    scope: global
    value: "{{git_username}}"

- name: Setup git user email
  git_config:
    name: user.email
    scope: global
    value: "{{git_email}}"

- name: Add GPG key
  ansible.builtin.shell:
    cmd: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BA31D57EF5975CA