---
apache_create_vhosts: true
apache_vhosts_filename: "starter.conf"
apache_vhosts_template: "vhosts.conf.j2"
apache_ignore_missing_ssl_certificate: false
apache_vhosts:
   - servername: "thestarter.net"
     serveralias: "www.thestarter.net"
     documentroot: "/var/www/html/thestarter.net/server/api/public"
     extra_parameters: |
      ErrorLog ${APACHE_LOG_DIR}/thestarter.net-error.log
      CustomLog ${APACHE_LOG_DIR}/thestarter.net-access.log combined

      RewriteEngine on
      RewriteCond %{SERVER_NAME} =www.thestarter.net [OR]
      RewriteCond %{SERVER_NAME} =thestarter.net
      RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

apache_vhosts_ssl:
  - {
     servername: "thestarter.net",
     documentroot: "/var/www/html/thestarter.net/server/api/public",
     certificate_file: "/etc/letsencrypt/live/thestarter.net/fullchain.pem",
     certificate_key_file: "/etc/letsencrypt/live/thestarter.net/privkey.pem"
  }
apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"
apache_mods_enabled:
  - rewrite.load
  - headers.load
  - proxy.load
  - proxy.conf
  - socache_shmcb.load
  - http2.conf
  - http2.load
  - ssl.conf
  - ssl.load
  - rewrite.load
  - expires.load
  - proxy_fcgi.load
  - proxy_http.load
  - wsgi.conf
  - wsgi.load
apache_mods_disabled: []
