---
- name: "Install other dependencies."
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl
    - unzip
    - sendmail
    - acl
    - moreutils

- name: "ensure SSH key is generated"
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa

# Set some settings in ~/.gitconfig
- name: setup git name
  git_config:
    name: user.name
    scope: global
    value: "ESOF Starter"
- name: setup git user email
  git_config:
    name: user.email
    scope: global
    value: esofstarter@gmail.com

- name: Ensure /var/www/html/thestarter.net directory for website exists
  file:
    path: "/var/www/html/thestarter.net"
    state: directory
    owner: www-data
    group: www-data
    mode: '0700'

- name: Copy .env file
  copy:
    src: "sensitive/.env"
    dest: "/var/www/html/thestarter.net/.env"
    owner: www-data
    group: www-data
    mode: '0644'